_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 5
                - 6
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.6
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": darwin-x86_64
        visualize:
            Decision Tree ROC Curve:
                panel_config:
                    fieldSettings:
                        lineKey: lineKey
                        lineVal: lineVal
                        step: step
                    panelDefId: wandb/lineseries/v0
                    stringSettings:
                        title: Decision Tree ROC Curve
                        xname: False Positive Rate
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Decision Tree ROC Curve_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
