# docker-compose.yml
      
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:latest
    ports:
      - "7000:7000" # Map Flask container port to host port
    environment:
      - API_KEY=${API_KEY} # Pass WANDB_API_KEY from local environment to the container
    volumes:
      - ./models:/models

  # Uncomment below to add the Streamlit container
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    volumes:
     - ./models:/models
    ports:
      - "8501:8501" # Map Streamlit container port to host port
    