_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "2":
                - 5
                - 6
                - 7
                - 8
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.6
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": darwin-x86_64
        visualize:
            AUC Bar Chart:
                panel_config:
                    fieldSettings:
                        label: Model
                        value: AUC
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: AUC Scores by Model
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: AUC Bar Chart_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
