_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.6
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": darwin-x86_64
        visualize:
            angle_only_roc_curve:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: False Positive Rate
                        "y": True Positive Rate
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: ROC Curve (angle_only)
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: angle_only_roc_curve_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
